version: "3.8"

services:
  db:
    image: postgres:16
    # ports:
    #   - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
  server: &node
    image: node:20
    command: sh -c 'npm i -w server && npm --workspace=server run dev'
    environment:
      PORT: 8787
      DATABASE_URL: postgres://postgres:postgres@db/postgres
    volumes:
      - node_modules:/app/node_modules
      - .:/app:delegated
    working_dir: /app
    depends_on:
      - db
  web:
    <<: *node
    ports:
      - "3000:3000"
    command: sh -c 'npm i -w web && npm --workspace=web run dev'
    environment:
      GRAPHQL_URL: http://server:8787/graphql
    depends_on:
      - server

volumes:
  pgdata:
  node_modules:
