import type { Metadata } from "next";
import { Providers } from "./Providers";
import { Container, Heading, Stack } from "@chakra-ui/react";
import Link from "next/link";

export const metadata: Metadata = {
  title: "ツイタ",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ja">
      <body>
        <Providers>
          <Container maxW="container.lg" pt={4} pb={12}>
            <Stack spacing={4} direction="column">
              <Link href="/">
                <Heading as="h1">ツイタ</Heading>
              </Link>
              <main>{children}</main>
            </Stack>
          </Container>
        </Providers>
      </body>
    </html>
  );
}
