import type { Metadata } from "next";
import { Providers } from "./Providers";
import { ChakraLayout } from "./ChakraLayout";

export const metadata: Metadata = {
  title: "ま",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ja">
      <body>
        <Providers>
          <ChakraLayout>{children}</ChakraLayout>
        </Providers>
      </body>
    </html>
  );
}
